### ISSUE TITLE
OCI Index Building Service

### ISSUE THREAD

**Issue by amouat** [Trow-Registry/trow#155]
At the moment, building a multi-arch image puts a lot of responsibility on the client. They have to build the separate images and then create an OCI index that points to the separate images. This is particularly problematic in CI builds, where servers of different archs are used to create the builds and you need to run a secondary pass to put them all together.

A lot of the problems could be alleviated by having an endpoint that automatically adds images to the appropriate OCI index e.g. `docker push myreg:5000/_builder/arm64/linux/myrepo/myimage:test would add an entry for arm64 and linux that can be pulled via `docker pull myreg:5000/myrepo/myimage:test`.

I have created a [Google doc](https://docs.google.com/document/d/1Dfwd6tUvRTTQKItD_AG-qmfJUbZQFk8_sut8P5RaOvY/edit?usp=sharing) that should be worked into a proper RFC.

**Comment by awoimbee** [comment]
Out of scope, let's first try to adhere to the OCI standard
