### ISSUE TITLE
Improve Install Docs

### ISSUE THREAD

**Issue by amouat** [Trow-Registry/trow#168]
The current install docs are a bit all over the place:

 -  The kustomize install instructions are under the `install` directory but the Helm instructions are under `docs`. I guess the best solution is to move the kustomize instructions but leave a placeholder in install pointing to the docs guide.
 - The Helm instructions could do with a bit more context and explanation, especially on TLS ingress and domain names. But some of this is already in the Kustomize instructions, so there might be a way to merge the two.
 - We should consider offering users some context of when to choose between the two. For example, would it be fair to say the Kustomize instructions are better for GitOps and if you need finer control?

**Comment by pradipta** [comment]
On it

**Comment by awoimbee** [comment]
Helm is now the only supported way, it's fully automated (auto generated TLS certs and such)
