### ISSUE TITLE
Consider hostctl for hosts management in quick-install

### ISSUE THREAD

**Issue by blaggacao** [Trow-Registry/trow#189]
https://guumaster.github.io/hostctl/ is a specialized tool that focuses on managing host entries in a reversible manner. While still modifying host state, it does so (easily) reversibly. &mdash; for `./quick-install`.

Breadcrumb trail: https://github.com/numtide/devshell/issues/27

**Comment by amouat** [comment]
Yeah, this is interesting. It is adding another dependency but is probably a better way of doing things, especially for the client end.

**Comment by amouat** [comment]
Also, I see it supports windows, which is nice!

**Comment by blaggacao** [comment]
If you would be willing to give github.com/numtide/devshell a try, I could be plugging together a prototype that would have unrivalled UX, and only _ever_ two bootstrap dependencies:

- `curl -L https://nixos.org/nix/install | sh`
- a nix command to fetch `devshell` binary, later a normally distributed binary of the devshell command

**Comment by blaggacao** [comment]
**Showcase:**

- &rarr; [wrapped hostctl](https://github.com/ContainerSolutions/trow/pull/193/files#diff-4bb450507124b9bcd863a6d4a8fff3a75338d9a11c2ced8bb59b33f3f73637b0R42-R61) &mdash; `nix-shell`
- &rarr; [fed by `devshell.toml`](https://github.com/ContainerSolutions/trow/pull/193/files#diff-04359bb04ecc08b0f19f634f869be71b73a5585e69c0f762403232b8ba6db226R91) &mdash; `nix-shell`

**Comment by awoimbee** [comment]
Helm is now the only supported way to deploy Trow
