### ISSUE TITLE
A full "deployment.yaml" file for reference in the documentation.

### ISSUE THREAD

**Issue by Christian-Rau** [Trow-Registry/trow#229]
**Is your feature request related to a problem? Please describe.**
Quick install is based on.. docker!?.. (Lets look forward, and we see no docker deamon out there :)
The documentation for helm lacks some explanation on how to get it up running fully in a k8s cluster.
The Kustomize install is way over the top, for a small application like this. - Supposed to be "light-weight"

**Describe the solution you'd like**
Have a step by step, description of ALL the moving parts in building up a basic deployment.yaml.
that start with:
```
apiVersion: v1
kind: Namespace
metadata:
  name: coolest-registry
---
E:T:C.
```
apiVersion:

**Describe alternatives you've considered**
ALL, however as I want to build/learn the future foundation of clusters, it has to go without docker.

**Additional context**

**Comment by amouat** [comment]
So there's a few separate issues here:

1) Quick install shouldn't depend on Docker. You're right. I've done some work in the past to get it to work with containerd and kept hitting problems regarding how registries are handled. I think there's still a big problem in that adding a secure registry config to containerd requires restarting containerd, which is a pain, especially on managed solutions like GKE. This is absolutely something we want to look at and fix though, and it's something I have spent a lot of time looking at already. As you're probably aware, the kustomize and Helm installs don't require Docker, but they do require the user to configure DNS and/or routing.

2) Kustomize is too heavy. If you have ideas for taking things out, please let me know!

3) Step by step guide - I like this idea a lot. It would make a nice post, and I'll look into making it happen.

**Comment by awoimbee** [comment]
Closing this as helm is now the only way to deploy Trow.
The Helm chart should be quite easy to use but don't hesitate to open another issue if you feel it lacks documentation!
