### ISSUE TITLE
Project future: possible ownership transfert ?

### ISSUE THREAD

**Issue by awoimbee** [Trow-Registry/trow#344]
Hi,
This repo seems quite dead to me and IMO Trow is not all that useful without #329. Since opening #329 I continued iterating on Trow on my side: https://github.com/Extrality/trow/compare/edbdb1ae76bacf02899bd97be27f989859c2a588..main.

@amouat talked to me about the possibility of creating a Trow github organization to continue work on the project but it never came to fruition.

Does ContainerSolutions want to keep (and maintain) the repo or to transfert ownership ? To Extrality ?
Can [Extrality/trow](https://github.com/Extrality/trow) keep its name or should it be renamed (trademark issue) ?

**Comment by amouat** [comment]
@awoimbee let's create a Trow org. I'll find out who is in charge of repos at Container Solutions now and we can ask them to help move the repo. If that doesn't happen we'll just have to fork, which would be very sad.

**Comment by ianmiell** [comment]
Hey Adrian! I'm discussing this internally, hopefully I can get back to you soon.

**Comment by ianmiell** [comment]
Hey @amouat we're giving you access rights now, you should get a mail. LMK if you need anything more. Cheers, Ian

**Comment by DavidZisky** [comment]
@amouat ping ☝️

**Comment by amouat** [comment]
As an update, I don't have admin rights on this repo any more and can't really get anything done.

As it stands, I think the only will probably be to fork the repo.

**Comment by DavidZisky** [comment]
It's been a few months since @ianmiell mentioned giving you access, so I assume it has been revoked at some point since you didn't reply. If transferring ownership is preferable over forking, then we are happy to help with that. I'll ping Ian internally now to give you access again.

**Comment by DavidZisky** [comment]
Ok, I was told it will be sorted (the transfer) today. Apologies that it took so long. What about trow.io website? Do you have control over it (and the domain) @amouat ? Or should I ask around about that, too?

**Comment by amouat** [comment]
Thanks!

Good point about the domain, I'm not sure where that is...

**Comment by DavidZisky** [comment]
@amouat @awoimbee sent you both email, please take a look (putting it here in case you see github notification quicker ;p )

**Comment by DavidZisky** [comment]
Ok, looks like we're done! Please take good care of trow, apologies again that the transfer took so long and good luck with further development!

**Comment by amouat** [comment]
Thanks @DavidZisky !
