### ISSUE TITLE
[Bug]: Wrong Quickinstall link on website

### ISSUE THREAD

**Issue by mms-gianni** [Trow-Registry/trow#378]
### Describe the bug

Your qick install link on your main website is wrong (Both of them) . It points to: https://github.com/Trow-Registry/trow/blob/main/QUICK-INSTALL.md 

I suggest a link to this site : 
https://github.com/Trow-Registry/trow/blob/main/docs/HELM_INSTALL.md

**Comment by awoimbee** [comment]
Sadly I don't know who owns the website nor how it's managed

**Comment by amouat** [comment]
Oh, sorry. I'll take a look later. I think it's in GitHub tbh

**Comment by amouat** [comment]
It's here https://github.com/Trow-Registry/trow/tree/gh-pages

**Comment by amouat** [comment]
Ok, I've tried to update everything and remove the CS links & logos.

There's definitely a non-zero chance that I've made a mistake and the site will go down :)

Thanks @mms-gianni for the report.

@awoimbee feel free to update the webpage, you just need to push to the gh-pages branch.
