### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by amouat** [Trow-Registry/trow#68]
Trow should move to proper structured logs and have better, more consistent logging in general. This might be a little hampered by Rocket, which does its own logging (eventually I would like to move to Warp, but that will take some effort). 

The first task would be to investigate log & slog support for structured logs and how they can be integrated into Trow. Then we should figure out where logging should happen and what levels should be used when. A much standardised approach to logs is necessary.

Whilts this is a big issue, it can be tackled bit by bit and should be reasonably easy to get started.

**Comment by amouat** [comment]
Looking into this, it seems the tracing crate may be relevant and important: https://tracing-rs.netlify.app/tracing/ Also possibly relevant to #126 in the long run.

**Comment by amouat** [comment]
@iamcaleberic currently looking at this.

**Comment by amouat** [comment]
Another side of this is just figuring out what should be logged and where. 

I recently added #197 which added a bunch of log messages - we need to start thinking about how the logs can be used to debug problems and in general build up an idea of what's happening & the ordering of events.

**Comment by awoimbee** [comment]
Done since https://github.com/Trow-Registry/trow/commit/d7b9fade77d9846ad6950d9bcaab723dd7fdf086#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L53
