### ISSUE TITLE
Integrations with Kubernetes Distros & Installers

### ISSUE THREAD

**Issue by amouat** [Trow-Registry/trow#69]
One of the focuses of Trow is to be easy to install. To that end, we should try to integrate with other projects. These needs to go beyond just "works with", In a lot of cases we can aim to be a "plugin" or similar.

This should include:

[ ] minikube addon https://minikube.sigs.k8s.io/docs/handbook/deploying/#addons
[ ] microk8s addon https://microk8s.io/docs/addons#heading--list
[ ] kubestack install https://www.kubestack.com/catalog
[ ] arkade https://github.com/alexellis/arkade

**Comment by amouat** [comment]
If you want to work on any of these, please discuss here and then we can open a new issue for the specific platform.

**Comment by blaggacao** [comment]
I'm setting something up with k3d on #193

**Comment by awoimbee** [comment]
Not happening, we have helm
